# Generated by Django 4.0.1 on 2022-01-14 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('score', models.CharField(choices=[('one', '&#11088'), ('two', '&#11088&#11088'), ('three', '&#11088&#11088&#11088'), ('four', '&#11088&#11088&#11088&#11088'), ('five', '&#11088&#11088&#11088&#11088&#11088')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
