# Generated by Django 4.0.1 on 2022-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.CharField(choices=[('&#11088', '&#11088'), ('&#11088&#11088', '&#11088&#11088'), ('&#11088&#11088&#11088', '&#11088&#11088&#11088'), ('&#11088&#11088&#11088&#11088', '&#11088&#11088&#11088&#11088'), ('&#11088&#11088&#11088&#11088&#11088', '&#11088&#11088&#11088&#11088&#11088')], max_length=1000),
        ),
    ]
