# Generated by Django 4.0.1 on 2022-01-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_repassword',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
