# Generated by Django 4.0.1 on 2022-01-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_repassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user_nickid',
        ),
    ]
